org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric properties - https://fabricmc.net/develop
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.3
loader_version=0.18.2
loom_version=1.14-SNAPSHOT

# Mod properties
mod_version=1.0.0
maven_group=dev.maro
archives_base_name=maro

# Dependencies
fabric_version=0.141.6+1.21.11
client_gametest_api_version=4.3.5
